baseurl: "http://blog.nytoca.ch"

copyright: "asdf"
languageCode: en-us
MetaDataFormat: yaml
canonifyurls: true
theme: persona

PostFormat: true

blackfriday:
    Fractions: false
    Extensions:
        - noEmptyLineBeforeBlock
        - hardLineBreak

title: Nytoca´s Blog
author:
    name: Philipp Marmet

permalinks:
    post: /:year/:month/:day/:filename/
    page: /:filename/

paginate: 10
paginatepath: page

indexes:
   category: categories
   tag: tags

params:
  ShowTopProfile: true
  ShowTopSocial: false

  # Settings
  DateFormat: 2. Jan 2006

  edit_link_url: http://github.com/nytoca/blog.nytoca.ch/blob/master/content/
  #description: "Blogging about Programming, Security, Linux, Networking and Web Apps. Daily worklog"
  description: "Blogging about Linux, Networking and Web Apps. Daily worklog"
  logo: "/author/nytoca.jpg"

  Social:
      bitbucket: nytoca
      # gitlab: nytoca
      github: nytoca
      # flickr: nytoca
      # twitter: nytoca
      # facebook: nytoca
      # linkedin: nytoca
      email: info@nytoca.ch
      # skype: nytoca

  Authors:
    default: nytoca
    nytoca:
        Name: "Philipp Marmet"
        Link: "/author/nytoca/"
        Avatar: "/author/nytoca.jpg"
        ShortBio: "derp"
